// THIS FILE IS AUTO-GENERATED BY METACOUNTER. DO NOT EDIT.
#ifndef GENERATED_COUNTER_REGISTRY_H
#define GENERATED_COUNTER_REGISTRY_H

#include <stdint.h>

#ifdef __cplusplus

enum class CounterID : unsigned int {
    PlayerHealth = 0,
    PlayerStamina = 1,
    DrawCalls = 2,
    ShaderBinds = 3,
    TextureBinds = 4,
    MainRenderContext = 5,
    ActiveAudioChannels = 6,
    MAX_COUNT = 7
};

enum { MAX_COUNT_INT = 7 };

inline const char* get_name_for_CounterID(CounterID id) {
    static const char* names[] = {
        "PlayerHealth",
        "PlayerStamina",
        "DrawCalls",
        "ShaderBinds",
        "TextureBinds",
        "MainRenderContext",
        "ActiveAudioChannels",
    };
    unsigned int index = (unsigned int)id;
    if (index <= 6) return names[index];
    return "(invalid)";
}

#define REGISTER_COUNTER(name, ...) CounterID::name
#define REGISTER_UNIQUE_COUNTER(name, ...) CounterID::name

#else

typedef enum {
    CounterID_PlayerHealth = 0,
    CounterID_PlayerStamina = 1,
    CounterID_DrawCalls = 2,
    CounterID_ShaderBinds = 3,
    CounterID_TextureBinds = 4,
    CounterID_MainRenderContext = 5,
    CounterID_ActiveAudioChannels = 6,
    CounterID_MAX_COUNT = 7
} CounterID;

enum { MAX_COUNT_INT = 7 };

static inline const char* get_name_for_CounterID(CounterID id) {
    static const char* names[] = {
        "PlayerHealth",
        "PlayerStamina",
        "DrawCalls",
        "ShaderBinds",
        "TextureBinds",
        "MainRenderContext",
        "ActiveAudioChannels",
    };
    if ((unsigned int)id <= 6) return names[(unsigned int)id];
    return "(invalid)";
}

#define REGISTER_COUNTER(name, ...) CounterID_##name
#define REGISTER_UNIQUE_COUNTER(name, ...) CounterID_##name

#endif

#endif // GENERATED_COUNTER_REGISTRY_H
